name: Network Analysis

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  traceroute_and_dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Traceroute to github.com
        run: |
          echo "=== Traceroute ==="
          traceroute github.com

      - name: DNS Resolution for github.com
        run: |
          echo "=== DNS Resolution ==="
          dig github.com

  packet_capture:
    runs-on: ubuntu-latest
    needs: traceroute_and_dns
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Capture DNS Traffic
        run: |
          echo "=== Packet Capture ==="
          sudo timeout 10 tcpdump -c 5 -i any 'port 53' -nn

  reverse_dns_lookup:
    runs-on: ubuntu-latest
    needs: packet_capture
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reverse DNS Lookup for 8.8.4.4
        run: |
          echo "=== Reverse DNS Lookup ==="
          dig -x 8.8.4.4

      - name: Reverse DNS Lookup for 1.1.2.2
        run: |
          dig -x 1.1.2.2
